version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: core_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - solr
    links:
      - solr      
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: core_production_postgres
    volumes:
      - ../scms_data/scielo_core/data_prod:/var/lib/postgresql/data:Z
      - ../scms_data/scielo_core/data_prod_backup:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.production/.postgres
  
  solr:
      image: solr:9.3
      restart: always
      ports:
         - "8983:8983"
      volumes:
          - ./index/data:/var/solr
      environment:
          - SOLR_JAVA_MEM=-Xms512m -Xmx512m
          - SOLR_HEAP=512m
  
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: core_production_traefik
    depends_on:
      - django
    volumes:
      - ../scms_data/scielo_core/traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: core_production_celeryworker
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: core_production_celerybeat
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat

  flower:
    <<: *django
    image: core_production_flower
    command: /start-flower

  celery-exporter:
    image: danihodovic/celery-exporter
    restart: always
    ports:
     - 9808:9808
    command: ["--broker-url=redis://redis:6379/0"]
    depends_on:
     - redis

  victoriametrics:
    image: victoriametrics/victoria-metrics
    restart: always
    ports:
      - 8428:8428